allow passing script args

diff --git a/script/start b/script/start
--- a/script/start
+++ b/script/start
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
-set -e
+set -euo pipefail
 
 NETWORK_VOLUME_PATH=${1:-"/Volumes/SG WD 2TB S"}
+QBITTORRENT_DOWNLOAD_PATH=${2:-"/Users/stephengeller/Downloads/Torrents/qbittorrent"}
 
 # Check that the drive is mounted
 if ! (mount | grep "on ${NETWORK_VOLUME_PATH}" > /dev/null); then
@@ -10,11 +11,18 @@ if ! (mount | grep "on ${NETWORK_VOLUME_PATH}" > /dev/null); then
     exit 1
 fi
 
+if [ ! -d "$QBITTORRENT_DOWNLOAD_PATH" ]; then
+  echo -e "\033[31;1mERROR: \033[0;31mTemporary download path ${QBITTORRENT_DOWNLOAD_PATH} does not exist\033[0m"
+  exit 1
+fi
+
 # Check that all mounted volumes have correct permissions
 # sudo chmod 777 ~/Downloads/Torrents/qbittorrent
 
 # Spin up services
-NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" docker-compose up -d
+NETWORK_VOLUME_PATH="${NETWORK_VOLUME_PATH}" \
+  QBITTORRENT_DOWNLOAD_PATH="${QBITTORRENT_DOWNLOAD_PATH}" \
+  docker-compose up -d
 
 # Open websites
 #open http://localhost:8989
